# Generated by Django 4.0.1 on 2022-07-16 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('JKNGO', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='List',
        ),
    ]
