# Generated by Django 4.0.1 on 2022-07-16 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JKNGO', '0003_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=200)),
                ('password', models.CharField(max_length=200)),
                ('phonenumber', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=254)),
                ('city', models.CharField(max_length=20)),
            ],
        ),
        migrations.DeleteModel(
            name='user',
        ),
    ]
